Updated top-level scripts - removed obsolete capistrano script, Made bash alias generator Mac friendly Added checks to sandbox script Abstracted server_setup to be work for all users

diff --git a/install_sandbox b/install_sandbox
--- a/install_sandbox
+++ b/install_sandbox
@@ -1,9 +1,15 @@
 #!/bin/bash
 
-mysql_version=$(mysql -V | awk '{print $5}' | sed -s 's/,//')
+mysql_version=5.5.17
+#mysql_version=$(mysql -V | awk '{print $5}' | sed -s 's/,//')
 
 EXPECTED_ARGS=2
 E_BADARGS=65
+
+if [ ! -d "/db" ]; then
+  echo "Unable to create sandbox - sandbox directory not found, expected /db"
+  exit 1
+fi
 
 if [ $# -ne $EXPECTED_ARGS ]
 then
